/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlayQuestionIdRouteImport } from './routes/play/$questionId'
import { Route as ApiSubmitAnswerRouteImport } from './routes/api/submit-answer'
import { Route as ApiGradeAnswerRouteImport } from './routes/api/grade-answer'
import { Route as ApiExecuteCodeRouteImport } from './routes/api/execute-code'
import { Route as ApiSessionCreateRouteImport } from './routes/api/session/create'
import { Route as ApiQuestionsNextRouteImport } from './routes/api/questions/next'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuestionIdRoute = PlayQuestionIdRouteImport.update({
  id: '/play/$questionId',
  path: '/play/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitAnswerRoute = ApiSubmitAnswerRouteImport.update({
  id: '/api/submit-answer',
  path: '/api/submit-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradeAnswerRoute = ApiGradeAnswerRouteImport.update({
  id: '/api/grade-answer',
  path: '/api/grade-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteCodeRoute = ApiExecuteCodeRouteImport.update({
  id: '/api/execute-code',
  path: '/api/execute-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionCreateRoute = ApiSessionCreateRouteImport.update({
  id: '/api/session/create',
  path: '/api/session/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsNextRoute = ApiQuestionsNextRouteImport.update({
  id: '/api/questions/next',
  path: '/api/questions/next',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/execute-code': typeof ApiExecuteCodeRoute
  '/api/grade-answer': typeof ApiGradeAnswerRoute
  '/api/submit-answer': typeof ApiSubmitAnswerRoute
  '/play/$questionId': typeof PlayQuestionIdRoute
  '/play': typeof PlayIndexRoute
  '/api/questions/next': typeof ApiQuestionsNextRoute
  '/api/session/create': typeof ApiSessionCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/execute-code': typeof ApiExecuteCodeRoute
  '/api/grade-answer': typeof ApiGradeAnswerRoute
  '/api/submit-answer': typeof ApiSubmitAnswerRoute
  '/play/$questionId': typeof PlayQuestionIdRoute
  '/play': typeof PlayIndexRoute
  '/api/questions/next': typeof ApiQuestionsNextRoute
  '/api/session/create': typeof ApiSessionCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/execute-code': typeof ApiExecuteCodeRoute
  '/api/grade-answer': typeof ApiGradeAnswerRoute
  '/api/submit-answer': typeof ApiSubmitAnswerRoute
  '/play/$questionId': typeof PlayQuestionIdRoute
  '/play/': typeof PlayIndexRoute
  '/api/questions/next': typeof ApiQuestionsNextRoute
  '/api/session/create': typeof ApiSessionCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/execute-code'
    | '/api/grade-answer'
    | '/api/submit-answer'
    | '/play/$questionId'
    | '/play'
    | '/api/questions/next'
    | '/api/session/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/execute-code'
    | '/api/grade-answer'
    | '/api/submit-answer'
    | '/play/$questionId'
    | '/play'
    | '/api/questions/next'
    | '/api/session/create'
  id:
    | '__root__'
    | '/'
    | '/api/execute-code'
    | '/api/grade-answer'
    | '/api/submit-answer'
    | '/play/$questionId'
    | '/play/'
    | '/api/questions/next'
    | '/api/session/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExecuteCodeRoute: typeof ApiExecuteCodeRoute
  ApiGradeAnswerRoute: typeof ApiGradeAnswerRoute
  ApiSubmitAnswerRoute: typeof ApiSubmitAnswerRoute
  PlayQuestionIdRoute: typeof PlayQuestionIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ApiQuestionsNextRoute: typeof ApiQuestionsNextRoute
  ApiSessionCreateRoute: typeof ApiSessionCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$questionId': {
      id: '/play/$questionId'
      path: '/play/$questionId'
      fullPath: '/play/$questionId'
      preLoaderRoute: typeof PlayQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-answer': {
      id: '/api/submit-answer'
      path: '/api/submit-answer'
      fullPath: '/api/submit-answer'
      preLoaderRoute: typeof ApiSubmitAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grade-answer': {
      id: '/api/grade-answer'
      path: '/api/grade-answer'
      fullPath: '/api/grade-answer'
      preLoaderRoute: typeof ApiGradeAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute-code': {
      id: '/api/execute-code'
      path: '/api/execute-code'
      fullPath: '/api/execute-code'
      preLoaderRoute: typeof ApiExecuteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/create': {
      id: '/api/session/create'
      path: '/api/session/create'
      fullPath: '/api/session/create'
      preLoaderRoute: typeof ApiSessionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/next': {
      id: '/api/questions/next'
      path: '/api/questions/next'
      fullPath: '/api/questions/next'
      preLoaderRoute: typeof ApiQuestionsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExecuteCodeRoute: ApiExecuteCodeRoute,
  ApiGradeAnswerRoute: ApiGradeAnswerRoute,
  ApiSubmitAnswerRoute: ApiSubmitAnswerRoute,
  PlayQuestionIdRoute: PlayQuestionIdRoute,
  PlayIndexRoute: PlayIndexRoute,
  ApiQuestionsNextRoute: ApiQuestionsNextRoute,
  ApiSessionCreateRoute: ApiSessionCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
