/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsNetworkingIndexRouteImport } from './routes/questions/networking/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as QuestionsNetworkingInternetIndexRouteImport } from './routes/questions/networking/internet/index'
import { Route as QuestionsNetworkingDhcpIndexRouteImport } from './routes/questions/networking/dhcp/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsNetworkingIndexRoute =
  QuestionsNetworkingIndexRouteImport.update({
    id: '/questions/networking/',
    path: '/questions/networking/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsNetworkingInternetIndexRoute =
  QuestionsNetworkingInternetIndexRouteImport.update({
    id: '/questions/networking/internet/',
    path: '/questions/networking/internet/',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuestionsNetworkingDhcpIndexRoute =
  QuestionsNetworkingDhcpIndexRouteImport.update({
    id: '/questions/networking/dhcp/',
    path: '/questions/networking/dhcp/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/networking': typeof QuestionsNetworkingIndexRoute
  '/questions/networking/dhcp': typeof QuestionsNetworkingDhcpIndexRoute
  '/questions/networking/internet': typeof QuestionsNetworkingInternetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/networking': typeof QuestionsNetworkingIndexRoute
  '/questions/networking/dhcp': typeof QuestionsNetworkingDhcpIndexRoute
  '/questions/networking/internet': typeof QuestionsNetworkingInternetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/networking/': typeof QuestionsNetworkingIndexRoute
  '/questions/networking/dhcp/': typeof QuestionsNetworkingDhcpIndexRoute
  '/questions/networking/internet/': typeof QuestionsNetworkingInternetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/questions/networking'
    | '/questions/networking/dhcp'
    | '/questions/networking/internet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/questions/networking'
    | '/questions/networking/dhcp'
    | '/questions/networking/internet'
  id:
    | '__root__'
    | '/'
    | '/api/auth/$'
    | '/questions/networking/'
    | '/questions/networking/dhcp/'
    | '/questions/networking/internet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  QuestionsNetworkingIndexRoute: typeof QuestionsNetworkingIndexRoute
  QuestionsNetworkingDhcpIndexRoute: typeof QuestionsNetworkingDhcpIndexRoute
  QuestionsNetworkingInternetIndexRoute: typeof QuestionsNetworkingInternetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/networking/': {
      id: '/questions/networking/'
      path: '/questions/networking'
      fullPath: '/questions/networking'
      preLoaderRoute: typeof QuestionsNetworkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/networking/internet/': {
      id: '/questions/networking/internet/'
      path: '/questions/networking/internet'
      fullPath: '/questions/networking/internet'
      preLoaderRoute: typeof QuestionsNetworkingInternetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/networking/dhcp/': {
      id: '/questions/networking/dhcp/'
      path: '/questions/networking/dhcp'
      fullPath: '/questions/networking/dhcp'
      preLoaderRoute: typeof QuestionsNetworkingDhcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  QuestionsNetworkingIndexRoute: QuestionsNetworkingIndexRoute,
  QuestionsNetworkingDhcpIndexRoute: QuestionsNetworkingDhcpIndexRoute,
  QuestionsNetworkingInternetIndexRoute: QuestionsNetworkingInternetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
